export const initialRows = [
    {
        id: 1,
        merchant: 'TEST1',
        client: 'Damien',
        lookup_source_type:'test1',
        descriptor: 'up_to_25_characters',
        issuer:'test1',
        report_start_date:'2023/02/03',
        report_end_date:'2023/02/04',
        acquirer_bin:'test',
        caid: 'vgftr',
        authorization_code:'code',
        acquirer: 'SIL',
        mid: 6725,
        order_match_flag:'flag',
        issue_int_name:'name',
        insight_id:'id',
        oi_digital_flag:'oi',
        lookup_date: '2023/02/03',
        deflection_settled_date:'2023/02/03',
        transaction_type:'online',
        order_id:'id',
        delfection_eligible_flag:'asf',
        amount:'123',
        currency:'USD',
        transation_request_id:'id',
        card_bin:'bin',
        card_last_four:'four',
    },
    {
        id: 2,
        merchant: 'TEST2',
        client: 'Damien',
        lookup_source_type:'test1',
        descriptor: 'up_to_25_characters',
        issuer:'test1',
        report_start_date:'2023/02/03',
        report_end_date:'2023/02/04',
        acquirer_bin:'test',
        caid: 'vgftr',
        authorization_code:'code',
        acquirer: 'SIL',
        mid: 6725,
        order_match_flag:'flag',
        issue_int_name:'name',
        insight_id:'id',
        oi_digital_flag:'oi',
        lookup_date: '2023/02/03',
        deflection_settled_date:'2023/02/03',
        transaction_type:'online',
        order_id:'id',
        delfection_eligible_flag:'asf',
        amount:'123',
        currency:'USD',
        transation_request_id:'id',
        card_bin:'bin',
        card_last_four:'four',
    },
    {
        id: 3,
        merchant: 'TEST3',
        client: 'Damien',
        lookup_source_type:'test1',
        descriptor: 'up_to_25_characters',
        issuer:'test1',
        report_start_date:'2023/02/03',
        report_end_date:'2023/02/04',
        acquirer_bin:'test',
        caid: 'vgftr',
        authorization_code:'code',
        acquirer: 'SIL',
        mid: 6725,
        order_match_flag:'flag',
        issue_int_name:'name',
        insight_id:'id',
        oi_digital_flag:'oi',
        lookup_date: '2023/02/03',
        deflection_settled_date:'2023/02/03',
        transaction_type:'online',
        order_id:'id',
        delfection_eligible_flag:'asf',
        amount:'123',
        currency:'USD',
        transation_request_id:'id',
        card_bin:'bin',
        card_last_four:'four',
    },
];