export const initialRows = [
    {
        id: 1,
        client: 'Damien',
        merchant: 'TEST3',
        rdrtier: 'test1',
        mcc: 'asd',
        email: 'atiurrahman@gmail.com',
        acquirer: 'SIL',
        mid: 6725,
        descriptor: 'up_to_25_characters',
        rdrstatus: 'Active',
        etocastatus: 'Active',
        caid: 'vgftr',
        midlive: '2023/03/02',
        bin: 'cdfvgtr',
        ethocalimit: 'mjkiuy'
    },
    {
        id: 2,
        client: 'Damien',
        merchant: 'TEST3',
        rdrtier: 'test1',
        mcc: 'asd',
        email: 'atiurrahman@gmail.com',
        acquirer: 'SIL',
        mid: 6725,
        descriptor: 'up_to_25_characters',
        rdrstatus: 'Active',
        etocastatus: 'Active',
        caid: 'bgrtfv',
        midlive: '2023/03/02',
        bin: 'sdcfvgr',
        ethocalimit: 'nhtgbfvr'
    },
    {
        id: 3,
        client: 'Damien',
        merchant: 'TEST3',
        rdrtier: 'test1',
        mcc: 'asd',
        email: 'atiurrahman@gmail.com',
        acquirer: 'SIL',
        mid: 6725,
        descriptor: 'up_to_25_characters',
        rdrstatus: 'Active',
        etocastatus: 'Active',
        caid: 'asdf',
        midlive: '2023/03/02',
        bin: 'vgbh',
        ethocalimit: 'vgbhty'
    },
];